
# Base packages
- name: Install core packages
  apt:
    name: "{{ core_packages }}"
    state: present
  vars:
    core_packages:
    - vim
    - git

# Root user configuration
- name: Copy root .bashrc configuration
  copy:
    src: root.bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: u=rw,g=r

- name: Copy root .profile configuration
  copy:
    src: shared.profile
    dest: /root/.profile
    owner: root
    group: root
    mode: u=rw,g=r

- name: Copy root .bash_aliases
  copy:
    src: shared.bash_aliases
    dest: /root/.bash_aliases
    owner: root
    group: root
    mode: u=rw,g=r

- name: Copy root .vimrc configuration
  copy:
    src: shared.vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: u=rw,g=r

# Administrative user configuration
- name: Copy admin .bashrc configuration
  copy:
    src: user.bashrc
    dest: /home/{{ admin_user }}/.bashrc
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: u=rw,g=r

- name: Copy admin .profile configuration
  copy:
    src: shared.profile
    dest: /home/{{ admin_user }}/.profile
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: u=rw,g=r

- name: Copy admin .bash_aliases
  copy:
    src: shared.bash_aliases
    dest: /home/{{ admin_user }}/.bash_aliases
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: u=rw,g=r

- name: Copy admin .vimrc configuration
  copy:
    src: shared.vimrc
    dest: /home/{{ admin_user }}/.vimrc
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: u=rw,g=r
