
_ansible: &ansible
  provider: ansible
  roles: kubernetes-admin
  directory: ansible
  servers:
    - name.startswith=kube-


cluster:
  <<: *ansible
  playbooks: cluster.yml

client:
  <<: *ansible
  playbooks: client.yml
