
cluster:
  provider: ansible
  roles: server-admin
  config: ansible.cfg
  group_vars: group_vars
  playbooks: playbooks/cluster.yml
  local_home_dir: /var/local/cenv

client:
  provider: ansible
  roles: server-admin
  config: ansible.cfg
  group_vars: group_vars
  playbooks: playbooks/client.yml
  local_home_dir: /var/local/cenv
