---
- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: Mount NFS share
  mount:
    fstype: nfs4
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    dump: "{{ item.dump | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"

- name: Update NFS mount permissions
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0777
    recurse: yes
  with_items: "{{ nfs_share_mounts }}"
