config:
  # Kubernetes core configurations
  kube_cluster_name: kube
  kube_service_addresses: 10.250.0.0/16
  kube_pods_subnet: 10.251.0.0/16

  kubelet_port: 10250
  kubelet_ro_port: 10255

  etcd_port_low: 2379
  etcd_port_high: 2380

  weave_port_low: 6783
  weave_port_high: 6784

  # Kubernetes master configurations
  kube_master_subnet_cidr_prefix: 28
  kube_master_subnet_public_ip: true

  aws_kube_master_subnets:
    - kube-master-1
    - kube-master-2
    - kube-master-3

  aws_kube_master_machine: t3.medium
  aws_kube_master_tenancy: default
  aws_kube_master_monitoring: false
  aws_kube_master_ebs_type: gp2
  aws_kube_master_ebs_size: 10
  aws_kube_master_ebs_iops: null
  aws_kube_master_ebs_optimized: false
  aws_kube_master_ebs_encrypted: false

  kube_master_api_port: 6443
  kube_master_scheduler_port: 10251
  kube_master_controller_port: 10252

  aws_load_balancer_timeout: 60
  aws_load_balancer_health_path: /healthz
  aws_load_balancer_healthy_status: 200
  aws_load_balancer_health_check_interval: 30
  aws_load_balancer_health_timeout: 10
  aws_load_balancer_healthy_threshold: 3
  aws_load_balancer_unhealthy_threshold: 3

  # Kubernetes node configurations
  kube_node_subnet_cidr_prefix: 20
  kube_node_subnet_public_ip: true

  aws_kube_node_subnets:
    - kube-node-1
    - kube-node-2
    - kube-node-3

  aws_kube_node_machine: t3.medium
  aws_kube_node_tenancy: default
  aws_kube_node_monitoring: false
  aws_kube_node_ebs_type: gp2
  aws_kube_node_ebs_size: 10
  aws_kube_node_ebs_iops: null
  aws_kube_node_ebs_optimized: false
  aws_kube_node_ebs_encrypted: false

  kube_node_nodeport_port_low: 30000
  kube_node_nodeport_port_high: 32767
