parents:
  - config

config:
  # Kubernetes master configurations
  aws_kube_master_subnets:
    - kube-master-1
    - kube-master-2
    - kube-master-3

  aws_kube_master_machine: t2.medium
  aws_kube_master_tenancy: default
  aws_kube_master_monitoring: false
  aws_kube_master_ebs_type: gp2
  aws_kube_master_ebs_size: 10
  aws_kube_master_ebs_iops: null
  aws_kube_master_ebs_optimized: false
  aws_kube_master_ebs_encrypted: false

  aws_load_balancer_timeout: 60
  aws_load_balancer_health_check_interval: 30
  aws_load_balancer_healthy_threshold: 3
  aws_load_balancer_unhealthy_threshold: 3

  # Kubernetes node configurations
  aws_kube_node_subnets:
    - kube-node-1
    - kube-node-2
    - kube-node-3

  aws_kube_node_machine: t2.medium
  aws_kube_node_tenancy: default
  aws_kube_node_monitoring: false
  aws_kube_node_ebs_type: gp2
  aws_kube_node_ebs_size: 10
  aws_kube_node_ebs_iops: null
  aws_kube_node_ebs_optimized: false
  aws_kube_node_ebs_encrypted: false
