---
- hosts: all
  roles:
    - { role: system-core }
    - { role: dev-sec.ssh-hardening }
  vars:
    admin_user: admin
    ssh_allow_users: admin

- name: Include Kubernetes tasks
  include: ../kubespray/cluster.yml

- name: Configure local Kubernetes utilities
  include: client.yml
